#cloud-config

bootcmd:
  # Technically not needed, but using it just for fun and reference
  # TODO: Add a timeout to avoid infinite loop
  - [ cloud-init-per, once, wait-for-disk, sh, -c, 'until [ -b /dev/disk/azure/scsi1/lun0 ]; do sleep 1; done' ]

package_update: true
package_upgrade: true

packages:
  - jq
  - acl

device_aliases: { data_disk: /dev/disk/azure/scsi1/lun0 }

disk_setup:
  data_disk:
    table_type: gpt
    layout: true
    overwrite: false

fs_setup:
  - label: DATA001
    filesystem: ext4
    device: data_disk
    partition: auto # TODO: Verify with explicit partition number is better

mounts:
  - [LABEL=DATA001, /data/disk001, "ext4", "defaults,nofail", "0", "2"]

runcmd:
  - [apt-get, autoremove, -y]
  - [apt-get, clean]

power_state:
  delay: 30
  mode: reboot
  message: Rebooting machine
  condition: test -f /var/tmp/reboot_me
